### PR TITLE
Newsletter subscribe

### PR DESCRIPTION
**Pull request by Mistaweng**

### CODE REVIEW

**Comment by Taiwopeter-babs** [comment]
There is a defined database schema and file structure for middlewares. Please view the `db.js` file and the `models` folder for database tables and queries.

**Comment by Taiwopeter-babs** [comment]
> There is a defined database schema and file structure for middlewares. Please view the `db.js` file and the `models` folder for database tables and queries.

And the query looks like it's from MongoDB. There is already a defined schema, or was it done for an additional editing from someone else?

**Review by Taiwopeter-babs — CHANGES_REQUESTED** [review]
mongoDB styles queries and db schema is used, which is not allowed.

**Review by hxnshaw — DISMISSED** [review]
The subscriber router doesn't have the necessary middleware. You can check the middlewares folder for it.

**Comment by Taiwopeter-babs** [comment]
> The subscriber router doesn't have the necessary middleware. You can check the middlewares folder for it.

I will add the middlewares and refactor the models and controllers.

**Review by Taiwopeter-babs — COMMENTED** [review]
The changes are expected to be made by another contributor. The reasons:
- The schema will be replaced with a mysql defined model

**Review by Taiwopeter-babs — APPROVED** [review]

**Pull request merged**
