### PR TITLE
errors when creating user routers.

### PR DESCRIPTION
**Pull request by hxnshaw**
The issue seems to be with 'bcrypt' from what I can see.

### CODE REVIEW

**Comment by Taiwopeter-babs** [comment]
> The issue seems to be with 'bcrypt' from what I can see.

I'll check this out now.

**Review by Taiwopeter-babs — COMMENTED** [review]
The code appears to be in order, but I don't knw why you have the `@types/bcrypt` package in `package.json`. The code is in JavaScript, not TypeScript.

**Comment by Taiwopeter-babs** [comment]
@VivianDee I made changes to the `users_courses` table; The `date_enrolled` column, which is a date type, does not support `knex.fn.now()`. a MySQL CURRENT_TIMESTAMP equivalent. Only `datetime` types support the function.

**Review by Taiwopeter-babs — APPROVED** [review]
Please take note
- Listening port was changed
- `date_enrolled` table in `users_courses` data type was changed `datetime`
- `package.json` was updated

**Review by VivianDee — COMMENTED** [review]
I've taken note of the changes. Great work 🙌

**Pull request merged**
