### PR TITLE
Database index

### PR DESCRIPTION
**Pull request by davidigbo**
## In this PR, the following functionalities have been implemented:

- Create indices (multiple index) for the database.
 > All ids must be indexed.
 > All email columns must be indexed.
 > The queries must be written in the schema.sql file.

### CODE REVIEW

**Review by Taiwopeter-babs — CHANGES_REQUESTED** [review]
This is good work. I have seen the corrections made regarding the indices. Please review the `modules` table name for the indices created.

**Review by VivianDee — DISMISSED** [review]
You did a good job but there is a mistake in the schema file. There is a column named "Id" and another named "course-id" within the courses table. Please change the "course_id" to "instructors_id" in accordance with the migration file.

Also, the instructors table does not need the "course_id".
The instructors table "id" is already populating the "instructors_id" section in the courses table.

**Review by Taiwopeter-babs — APPROVED** [review]
Good work. @david30-maker.

**Comment by Taiwopeter-babs** [comment]
> You did a good job but there is a mistake in the schema file. There is a column named "Id" and another named "course-id" within the courses table. Please change the "course_id" to "instructors_id" in accordance with the migration file.
> 
> Also, the instructors table does not need the "course_id". The instructors table "id" is already populating the "instructors_id" section in the courses table.

Shouldn't the `instructors` tables also have `course_id` in case of a query where the specified course the instructor is handling is requested by the admin?

**Pull request merged**
