### PR TITLE
morgan-logging

### PR DESCRIPTION
**Pull request by Mistaweng**

### CODE REVIEW

**Review by hxnshaw — APPROVED** [review]
Nice work!

**Review by Taiwopeter-babs — COMMENTED** [review]
Will the logger middleware catch the responses from the routers since it is used before the routers in the `app.js` file or should it be used for every controller?

**Comment by Mistaweng** [comment]
@Taiwopeter-babs, okay it's a global logging so what ever route you go to. It should log the response as well as the URL

**Comment by Taiwopeter-babs** [comment]
> @Taiwopeter-babs, okay it's a global logging so what ever route you go to. It should log the response as well as the URL

Does this mean the logger doesn't have to be used for every endpoint and used at the top level of the server?

**Pull request merged**
